export default {
  "Afrikaans": "af",
  "Albanian": "sq",
  "Arabic": "ar",
  "Armenian": "hy",
  "Azerbaijani": "az",
  "Basque": "eu",
  "Belarusian": "be",
  "Bengali": "bn",
  "Bosnian": "bs",
  "Bulgarian": "bg",
  "Catalan": "ca",
  "Chinese (Simplified)": "zh-CN",
  "Chinese (Traditional)": "zh-TW",
  "Croatian": "hr",
  "Czech": "cs",
  "Danish": "da",
  "Dutch": "nl",
  "English": "en",
  "English (United States)": "en-US",
  "English (United Kingdom)": "en-GB",
  "English (Australia)": "en-AU",
  "English (Canada)": "en-CA",
  "Estonian": "et",
  "Farsi": "fa",
  "Finnish": "fi",
  "French": "fr",
  "French (France)": "fr-FR",
  "French (Canada)": "fr-CA",
  "Galician": "gl",
  "Georgian": "ka",
  "German": "de",
  "German (Germany)": "de-DE",
  "Greek": "el",
  "Hebrew": "he",
  "Hindi": "hi",
  "Hungarian": "hu",
  "Icelandic": "is",
  "Indonesian": "id",
  "Irish": "ga",
  "Italian": "it",
  "Italian (Italy)": "it-IT",
  "Japanese": "ja",
  "Japanese (Japan)": "ja-JP",
  "Korean": "ko",
  "Korean (South Korea)": "ko-KR",
  "Latvian": "lv",
  "Lithuanian": "lt",
  "Macedonian": "mk",
  "Malay": "ms",
  "Malayalam": "ml",
  "Maltese": "mt",
  "Montenegrin": "sr-ME",
  "Norwegian": "no",
  "Norwegian Bokmål": "nb",
  "Norwegian Nynorsk": "nn",
  "Polish": "pl",
  "Portuguese": "pt",
  "Portuguese (Brazil)": "pt-BR",
  "Portuguese (Portugal)": "pt-PT",
  "Romanian": "ro",
  "Russian": "ru",
  "Russian (Russia)": "ru-RU",
  "Serbian": "sr",
  "Slovak": "sk",
  "Slovenian": "sl",
  "Spanish": "es",
  "Spanish (Spain)": "es-ES",
  "Spanish (Mexico)": "es-MX",
  "Swahili": "sw",
  "Swedish": "sv",
  "Tagalog": "tl",
  "Tamil": "ta",
  "Telugu": "te",
  "Thai": "th",
  "Turkish": "tr",
  "Ukrainian": "uk",
  "Urdu": "ur",
  "Vietnamese": "vi",
  "Welsh": "cy",
  "Yiddish": "yi"
};
