export default {
  "Afghanistan": "AF",
  "Albania": "AL",
  "Algeria": "DZ",
  "Andorra": "AD",
  "Angola": "AO",
  "Antigua and Barbuda": "AG",
  "Saudi Arabia": "SA",
  "Argentina": "AR",
  "Armenia": "AM",
  "Australia": "AU",
  "Austria": "AT",
  "Azerbaijan": "AZ",
  "Bahamas": "BS",
  "Bahrain": "BH",
  "Bangladesh": "BD",
  "Barbados": "BB",
  "Belgium": "BE",
  "Belize": "BZ",
  "Benin": "BJ",
  "Bhutan": "BT",
  "Belarus": "BY",
  "Myanmar": "MM",
  "Bolivia": "BO",
  "Bosnia and Herzegovina": "BA",
  "Botswana": "BW",
  "Brazil": "BR",
  "Brunei": "BN",
  "Bulgaria": "BG",
  "Burkina Faso": "BF",
  "Burundi": "BI",
  "Chile": "CL",
  "China": "CN",
  "Croatia": "HR",
  "Cyprus": "CY",
  "Chad": "TD",
  "Montenegro": "ME",
  "Czech Republic": "CZ",
  "Denmark": "DK",
  "Democratic Republic of the Congo": "CD",
  "Dominica": "DM",
  "Dominican Republic": "DO",
  "Djibouti": "DJ",
  "Egypt": "EG",
  "Ecuador": "EC",
  "Eritrea": "ER",
  "Estonia": "EE",
  "Ethiopia": "ET",
  "Fiji": "FJ",
  "Philippines": "PH",
  "Finland": "FI",
  "France": "FR",
  "Gabon": "GA",
  "Gambia": "GM",
  "Ghana": "GH",
  "Greece": "GR",
  "Grenada": "GD",
  "Georgia": "GE",
  "Guyana": "GY",
  "Guatemala": "GT",
  "Guinea": "GN",
  "Guinea-Bissau": "GW",
  "Equatorial Guinea": "GQ",
  "Haiti": "HT",
  "Spain": "ES",
  "Netherlands": "NL",
  "Honduras": "HN",
  "India": "IN",
  "Indonesia": "ID",
  "Iraq": "IQ",
  "Iran": "IR",
  "Ireland": "IE",
  "Iceland": "IS",
  "Israel": "IL",
  "Jamaica": "JM",
  "Japan": "JP",
  "Jordan": "JO",
  "Cambodia": "KH",
  "Cameroon": "CM",
  "Canada": "CA",
  "Qatar": "QA",
  "Kazakhstan": "KZ",
  "Kenya": "KE",
  "Kyrgyzstan": "KG",
  "Kiribati": "KI",
  "Colombia": "CO",
  "Comoros": "KM",
  "North Korea": "KP",
    "South Korea": "KR",
    "Kuwait": "KW",
    "Laos": "LA",
    "Lesotho": "LS",
    "Latvia": "LV",
    "Lebanon": "LB",
    "Liberia": "LR",
    "Libya": "LY",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Madagascar": "MG",
    "Malaysia": "MY",
    "Malawi": "MW",
    "Maldives": "MV",
    "Mali": "ML",
    "Malta": "MT",
    "Morocco": "MA",
    "Mauritius": "MU",
    "Mauritania": "MR",
    "Mexico": "MX",
    "Micronesia": "FM",
    "Moldova": "MD",
    "Monaco": "MC",
    "Mongolia": "MN",
    "Mozambique": "MZ",
    "Namibia": "NA",
    "Nauru": "NR",
    "Nepal": "NP",
    "Nicaragua": "NI",
    "Niger": "NE",
    "Nigeria": "NG",
    "Norway": "NO",
    "New Zealand": "NZ",
    "Oman": "OM",
    "Uganda": "UG",
    "Uzbekistan": "UZ",
    "Pakistan": "PK",
    "Panama": "PA",
    "Papua New Guinea": "PG",
    "Paraguay": "PY",
    "Peru": "PE",
    "Poland": "PL",
    "Portugal": "PT",
    "Republic of the Congo": "CG",
    "Macedonia": "MK",
    "Romania": "RO",
    "Russia": "RU",
    "Rwanda": "RW",
    "Saint Kitts and Nevis": "KN",
    "San Marino": "SM",
    "Saint Vincent and the Grenadines": "VC",
    "Saint Lucia": "LC",
    "Solomon Islands": "SB",
    "Samoa": "WS",
    "Sao Tome and Principe": "ST",
    "Senegal": "SN",
    "Serbia": "RS",
    "Seychelles": "SC",
    "Sierra Leone": "SL",
    "Singapore": "SG",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Somalia": "SO",
    "Sudan": "SD",
    "South Sudan": "SS",
    "Sri Lanka": "LK",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Suriname": "SR",
    "Syria": "SY",
    "Tajikistan": "TJ",
    "Tanzania": "TZ",
    "Thailand": "TH",
    "Timor-Leste": "TL",
    "Togo": "TG",
    "Tonga": "TO",
    "Trinidad and Tobago": "TT",
    "Tunisia": "TN",
    "Turkey": "TR",
    "Turkmenistan": "TM",
    "Tuvalu": "TV",
    "Ukraine": "UA",
    "Uruguay": "UY",
    "United States of America": "US",
    "Vanuatu": "VU",
    "Vatican City": "VA",
    "Venezuela": "VE",
    "Vietnam": "VN",
    "Yemen": "YE",
    "Zambia": "ZM",
    "Zimbabwe": "ZW"
};